name: CI
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.2.0
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm i --frozen-lockfile

      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx build --parallel=3 multi-step-form
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/multi-step-form/
